<?php

namespace App\Services;

use App\Models\Router;
use Illuminate\Support\Facades\Process;
use Illuminate\Support\Str;

class FreeRadiusClientSyncService
{
    /**
     * @return array{enabled: bool, path: string, desired_count: int, written: bool, reloaded: bool, content: string, errors: array<int,string>}
     */
    public function sync(bool $dryRun = false, bool $reload = false): array
    {
        $enabled = (bool) config('services.radius.manage_clients', false);
        $path = (string) config('services.radius.clients_file', '/etc/freeradius/3.0/clients.d/hotspotfreerad.conf');
        $content = $this->managedContent();

        $result = [
            'enabled' => $enabled,
            'path' => $path,
            'desired_count' => Router::query()->count(),
            'written' => false,
            'reloaded' => false,
            'content' => $content,
            'errors' => [],
        ];

        if (! $enabled || $dryRun) {
            return $result;
        }

        try {
            $directory = dirname($path);

            if (! is_dir($directory)) {
                mkdir($directory, 0775, true);
            }

            file_put_contents($path, $content, LOCK_EX);
            $result['written'] = true;
        } catch (\Throwable $exception) {
            $result['errors'][] = "Could not write FreeRADIUS clients file {$path}: ".$exception->getMessage();

            return $result;
        }

        if ($reload) {
            $command = (array) config('services.radius.reload_command', ['sudo', '-n', 'systemctl', 'reload', 'freeradius']);

            try {
                $reloadResult = Process::run($command);

                if ($reloadResult->successful()) {
                    $result['reloaded'] = true;
                } else {
                    $result['errors'][] = 'FreeRADIUS reload failed: '.trim($reloadResult->errorOutput() ?: $reloadResult->output());
                }
            } catch (\Throwable $exception) {
                $result['errors'][] = 'FreeRADIUS reload failed: '.$exception->getMessage();
            }
        }

        return $result;
    }

    public function managedContent(): string
    {
        $routers = Router::query()
            ->orderBy('wireguard_internal_ip')
            ->get(['id', 'name', 'nas_identifier', 'wireguard_internal_ip', 'shared_secret']);

        $lines = [
            '# Managed by HotspotFreeRAD. Do not edit this file manually.',
            '# Source: routers table. Regenerate with: php artisan hotspot:sync-radius-clients',
            '',
        ];

        foreach ($routers as $router) {
            if (blank($router->wireguard_internal_ip) || blank($router->shared_secret)) {
                continue;
            }

            $clientName = $this->clientName($router);
            $shortname = $this->quote($router->nas_identifier ?: $clientName);
            $secret = $this->quote((string) $router->shared_secret);

            $lines[] = "client {$clientName} {";
            $lines[] = "    ipaddr = {$router->wireguard_internal_ip}";
            $lines[] = "    secret = {$secret}";
            $lines[] = "    shortname = {$shortname}";
            $lines[] = '    nastype = mikrotik';
            $lines[] = "}";
            $lines[] = '';
        }

        return implode(PHP_EOL, $lines);
    }

    private function clientName(Router $router): string
    {
        $name = Str::of($router->nas_identifier ?: $router->name ?: 'router-'.$router->id)
            ->lower()
            ->replaceMatches('/[^a-z0-9_.-]+/', '-')
            ->trim('-')
            ->toString();

        return $name !== '' ? $name : 'router-'.$router->id;
    }

    private function quote(string $value): string
    {
        return '"'.str_replace(['\\', '"'], ['\\\\', '\\"'], $value).'"';
    }
}
