<?php

namespace App\Services;

/**
 * Generates a self-contained MikroTik RouterOS hotspot configuration that
 * does not depend on this platform at all -- no WireGuard, no HotspotFreeRAD
 * RADIUS server, no Router/Shop/Tenant record. Voucher validity is designed
 * to start counting from a customer's FIRST login, not from when the voucher
 * was created:
 *
 *  - RouterOS 7 uses the built-in User Manager (`/user-manager`) as a
 *    self-hosted local RADIUS server (pointed at 127.0.0.1 -- never leaves
 *    the router), whose `profile.starts-when=first-auth` is the officially
 *    documented way to do this. This is a materially different, richer
 *    object model than classic hotspot users (profile / limitation /
 *    profile-limitation / user-profile / user are five distinct objects),
 *    and it's what RouterOS 7 is designed for.
 *  - RouterOS 6 has no equivalent, so classic `/ip hotspot user` accounts
 *    are used instead, with an `on-login` script bound to the hotspot server
 *    profile that creates a one-time scheduler on a user's first login and
 *    removes the account when their validity window elapses. This is a
 *    well-established community pattern, not an official feature -- verify
 *    against real hardware before relying on it in production.
 *
 * Meant for the standalone "Script Generator" tool (super admin only) so
 * operators can configure any MikroTik -- with or without built-in
 * wireless, RouterOS 6 or 7 -- for a small hotspot business that isn't (or
 * isn't yet) a HotspotFreeRAD tenant.
 */
class StandaloneHotspotScriptGenerator
{
    /**
     * Character sets a voucher's username/password can be drawn from, mirroring
     * MikroTik's own batch-user dialog (username-characters/password-characters).
     * "safe" excludes characters easily confused when handwritten or misread off
     * a receipt (0/O, 1/I/l).
     */
    public const CHARACTER_SETS = [
        'alnum_safe' => 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789',
        'numeric' => '0123456789',
        'alpha_safe' => 'ABCDEFGHJKLMNPQRSTUVWXYZ',
        'alnum_full' => 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789',
    ];

    /**
     * @param  array{
     *     router_identity: string,
     *     hotspot_name: string,
     *     ros_version: string,
     *     has_wireless: bool,
     *     wan_port: string,
     *     ethernet_port_count: int,
     *     wireless_interface: string,
     *     hotspot_network: string,
     *     enable_mgmt_network: bool,
     *     mgmt_network: string,
     *     mgmt_password: string,
     *     profiles: list<array{name: string, download_mbps: int, upload_mbps: int, session_minutes: int, shared_users: int, voucher_count: int, voucher_prefix: string, voucher_code_length: int, voucher_username_password_same: bool, voucher_character_set: string}>,
     * } $config
     * @return array{script: string, vouchers: list<array{profile: string, username: string, password: string}>}
     */
    public function generate(array $config): array
    {
        $vouchers = $this->generateVoucherCodes($config['profiles']);

        $lines = array_merge(
            $this->headerLines($config),
            $this->identityAndBridgeLines($config),
            $this->wanLines($config),
            $this->hotspotNetworkLines($config),
            $this->wirelessLines($config),
            $this->managementNetworkLines($config),
            $this->firewallLines($config),
            $this->userSystemLines($config, $vouchers),
        );

        return [
            'script' => implode("\n", array_filter($lines, fn ($line) => $line !== null)),
            'vouchers' => $vouchers,
        ];
    }

    /**
     * @return list<string>
     */
    private function headerLines(array $config): array
    {
        return [
            '# Standalone MikroTik hotspot script -- generated by HotspotFreeRAD Script Generator',
            '# RouterOS '.$config['ros_version'].' / '.($config['has_wireless'] ? 'built-in wireless' : 'wired-only').' router',
            '# This script is self-contained: it does not use this platform\'s RADIUS, WireGuard, or any HotspotFreeRAD account.',
            '# Review port names (WAN/LAN) against your actual router before pasting.',
            '',
        ];
    }

    /**
     * @return list<string>
     */
    private function identityAndBridgeLines(array $config): array
    {
        $lines = [
            '/system identity set name="'.$this->quote($config['router_identity']).'"',
            '/interface bridge add name=bridge-hotspot comment="HotspotFreeRAD standalone hotspot bridge"',
        ];

        foreach ($this->lanPorts($config['wan_port'], (int) $config['ethernet_port_count']) as $port) {
            $lines[] = '/interface bridge port add bridge=bridge-hotspot interface='.$port;
        }

        $lines[] = '';

        return $lines;
    }

    /**
     * @return list<string>
     */
    private function wanLines(array $config): array
    {
        return [
            '/interface list add name=WAN comment="Internet uplink"',
            '/interface list member add list=WAN interface='.$config['wan_port'],
            '/ip dhcp-client remove [find interface='.$config['wan_port'].']',
            '/ip dhcp-client add interface='.$config['wan_port'].' add-default-route=yes disabled=no',
            '',
        ];
    }

    /**
     * @return list<string>
     */
    private function hotspotNetworkLines(array $config): array
    {
        $network = $this->networkParts($config['hotspot_network']);
        $useRadius = $config['ros_version'] === '7';

        return [
            '/ip address add address='.$network['gateway'].'/24 interface=bridge-hotspot',
            '/ip pool add name=pool-hotspot ranges='.$network['range'],
            '/ip dhcp-server add name=dhcp-hotspot interface=bridge-hotspot address-pool=pool-hotspot lease-time=30m disabled=no',
            '/ip dhcp-server network add address='.$network['cidr'].' gateway='.$network['host'].' dns-server=1.1.1.1,8.8.8.8',
            '/ip dns set allow-remote-requests=yes servers=1.1.1.1,8.8.8.8',
            '/ip hotspot profile add name=hotspot-profile hotspot-address='.$network['host'].' dns-name=hotspot.local login-by=http-pap,cookie'
                .($useRadius ? ' use-radius=yes' : ''),
            '/ip hotspot add name=hotspot1 interface=bridge-hotspot address-pool=pool-hotspot profile=hotspot-profile disabled=no',
            '/ip firewall nat add chain=srcnat out-interface='.$config['wan_port'].' action=masquerade',
            '',
        ];
    }

    /**
     * @return list<string>
     */
    private function wirelessLines(array $config): array
    {
        if (! $config['has_wireless']) {
            return [
                '# No built-in wireless -- attach an external access point to a LAN port broadcasting an open SSID for the hotspot.',
                '',
            ];
        }

        $interface = $config['wireless_interface'];
        $ssid = $this->quote($config['hotspot_name']);

        if ($config['ros_version'] === '6') {
            return [
                '/interface wireless security-profiles add name=hotspot-open mode=none',
                '/interface wireless set '.$interface.' mode=ap-bridge ssid="'.$ssid.'" security-profile=hotspot-open disabled=no',
                '/interface bridge port add bridge=bridge-hotspot interface='.$interface,
                '',
            ];
        }

        return [
            '/interface wifi security add name=hotspot-open authentication-types=""',
            '/interface wifi configuration add name=hotspot-open-cfg mode=ap ssid="'.$ssid.'" security=hotspot-open',
            '/interface wifi set [find default-name='.$interface.'] configuration=hotspot-open-cfg disabled=no',
            '/interface bridge port add bridge=bridge-hotspot interface='.$interface,
            '',
        ];
    }

    /**
     * @return list<string>
     */
    private function managementNetworkLines(array $config): array
    {
        if (! $config['enable_mgmt_network']) {
            return [
                '# Management network is disabled -- administer this router over its main LAN/WAN address only.',
                '',
            ];
        }

        $network = $this->networkParts($config['mgmt_network']);
        $lines = [
            '/interface bridge add name=bridge-mgmt comment="HotspotFreeRAD standalone management bridge, isolated from hotspot clients"',
            '/ip address add address='.$network['gateway'].'/24 interface=bridge-mgmt',
            '/ip pool add name=pool-mgmt ranges='.$network['range'],
            '/ip dhcp-server add name=dhcp-mgmt interface=bridge-mgmt address-pool=pool-mgmt lease-time=8h disabled=no',
            '/ip dhcp-server network add address='.$network['cidr'].' gateway='.$network['host'].' dns-server=1.1.1.1,8.8.8.8',
        ];

        if (! $config['has_wireless']) {
            $lines[] = '# Wire a dedicated port to bridge-mgmt for management access (this router has no built-in wireless for a management SSID).';
        } else {
            $interface = $config['wireless_interface'].'-mgmt';
            $password = $this->quote($config['mgmt_password']);

            if ($config['ros_version'] === '6') {
                $lines[] = '/interface wireless security-profiles add name=mgmt-sec mode=dynamic-keys authentication-types=wpa2-psk wpa2-pre-shared-key="'.$password.'"';
                $lines[] = '/interface wireless add name='.$interface.' master-interface='.$config['wireless_interface'].' ssid="'.$this->quote($config['hotspot_name'].' Mgmt').'" security-profile=mgmt-sec disabled=no';
            } else {
                $lines[] = '/interface wifi security add name=mgmt-sec authentication-types=wpa2-psk,wpa3-psk passphrase="'.$password.'"';
                $lines[] = '/interface wifi configuration add name=mgmt-cfg mode=ap ssid="'.$this->quote($config['hotspot_name'].' Mgmt').'" security=mgmt-sec';
                $lines[] = '/interface wifi add name='.$interface.' master-interface='.$config['wireless_interface'].' configuration=mgmt-cfg disabled=no';
            }

            $lines[] = '/interface bridge port add bridge=bridge-mgmt interface='.$interface;
        }

        $lines[] = '# Lock the router\'s own admin services to the management network only.';
        $lines[] = '/ip service set www address='.$network['cidr'];
        $lines[] = '/ip service set www-ssl address='.$network['cidr'];
        $lines[] = '/ip service set winbox address='.$network['cidr'];
        $lines[] = '/ip service set ssh address='.$network['cidr'];
        $lines[] = '';

        return $lines;
    }

    /**
     * @return list<string>
     */
    private function firewallLines(array $config): array
    {
        $lines = [
            '/ip firewall filter add chain=input connection-state=established,related action=accept',
            '/ip firewall filter add chain=input connection-state=invalid action=drop',
            '/ip firewall filter add chain=input in-interface=bridge-hotspot protocol=tcp dst-port=80,443,8080 action=accept comment="Hotspot captive portal ports"',
            '/ip firewall filter add chain=input in-interface-list=!WAN action=drop comment="Block other router access from hotspot clients"',
        ];

        if ($config['enable_mgmt_network']) {
            $lines[] = '/ip firewall filter add chain=input in-interface=bridge-mgmt action=accept comment="Allow the management network to reach the router"';
            $mgmtNetwork = $this->networkParts($config['mgmt_network']);
            $lines[] = '/ip firewall filter add chain=forward src-address=bridge-hotspot dst-address='.$mgmtNetwork['cidr'].' action=drop comment="Hotspot clients cannot reach the management network"';
        }

        $lines[] = '';

        return $lines;
    }

    /**
     * Branches on RouterOS version: v7 gets User Manager (profile.starts-when
     * = first-auth is the documented way to make validity start on first
     * login); v6 gets classic hotspot users plus an on-login scheduler script
     * that approximates the same behaviour.
     *
     * @param  list<array{name: string, download_mbps: int, upload_mbps: int, session_minutes: int, shared_users: int, voucher_count: int}>  $profiles
     * @param  list<array{profile: string, username: string, password: string}>  $vouchers
     * @return list<string>
     */
    private function userSystemLines(array $config, array $vouchers): array
    {
        return $config['ros_version'] === '7'
            ? $this->userManagerLines($config['profiles'], $vouchers)
            : $this->classicHotspotLines($config['profiles'], $vouchers);
    }

    /**
     * @param  list<array{name: string, download_mbps: int, upload_mbps: int, shared_users: int}>  $profiles
     * @param  list<array{profile: string, username: string, password: string}>  $vouchers
     * @return list<string>
     */
    private function userManagerLines(array $profiles, array $vouchers): array
    {
        $secret = bin2hex(random_bytes(12));
        $sharedUsersByProfile = collect($profiles)->pluck('shared_users', 'name');

        $lines = [
            '# RouterOS 7 User Manager -- a local, self-hosted RADIUS server (127.0.0.1 only, never leaves the router).',
            '# starts-when=first-auth means voucher validity counts from first login, not from creation.',
            '/user-manager set enabled=yes',
            '/user-manager router add address=127.0.0.1 name=this-router shared-secret="'.$secret.'"',
            '/radius add address=127.0.0.1 secret="'.$secret.'" service=hotspot',
            '',
        ];

        foreach ($profiles as $profile) {
            $slug = $this->profileIdentifier($profile['name']);
            $validityMinutes = max(1, (int) $profile['session_minutes']);

            $lines[] = '/user-manager limitation add name="'.$slug.'-limit" rate-limit-rx='.$profile['upload_mbps'].'M rate-limit-tx='.$profile['download_mbps'].'M';
            $lines[] = '/user-manager profile add name="'.$slug.'" validity='.$validityMinutes.'m starts-when=first-auth';
            $lines[] = '/user-manager profile-limitation add profile="'.$slug.'" limitation="'.$slug.'-limit"';
        }

        if ($vouchers !== []) {
            $lines[] = '';
            $lines[] = '# Voucher codes -- also listed on the printable sheet';

            foreach ($vouchers as $voucher) {
                $slug = $this->profileIdentifier($voucher['profile']);
                $sharedUsers = max(1, (int) ($sharedUsersByProfile[$voucher['profile']] ?? 1));

                $lines[] = '/user-manager user add name="'.$voucher['username'].'" password="'.$voucher['password'].'" shared-users='.$sharedUsers;
                $lines[] = '/user-manager user-profile add user="'.$voucher['username'].'" profile="'.$slug.'"';
            }
        }

        return $lines;
    }

    /**
     * @param  list<array{name: string, download_mbps: int, upload_mbps: int, session_minutes: int, shared_users: int}>  $profiles
     * @param  list<array{profile: string, username: string, password: string}>  $vouchers
     * @return list<string>
     */
    private function classicHotspotLines(array $profiles, array $vouchers): array
    {
        $lines = [
            '# Classic hotspot users (RouterOS 6 has no User Manager v7). The on-login script below',
            '# starts each voucher\'s validity countdown at first login rather than at creation --',
            '# a well-established community pattern, not an official feature. Verify on real hardware.',
            '/ip hotspot profile set hotspot-profile on-login="'.$this->onLoginExpiryScript().'"',
            '',
        ];

        foreach ($profiles as $profile) {
            $slug = $this->profileIdentifier($profile['name']);
            $rateLimit = $profile['upload_mbps'].'M/'.$profile['download_mbps'].'M';
            $sessionTimeout = max(1, (int) $profile['session_minutes']) * 60;

            $lines[] = '/ip hotspot user profile add name="'.$slug.'" rate-limit='.$rateLimit.' session-timeout='.$sessionTimeout.'s shared-users='.max(1, (int) $profile['shared_users']);
        }

        if ($vouchers !== []) {
            $lines[] = '';
            $lines[] = '# Voucher codes -- also listed on the printable sheet';

            foreach ($vouchers as $voucher) {
                $lines[] = '/ip hotspot user add name="'.$voucher['username'].'" password="'.$voucher['password'].'" profile="'.$this->profileIdentifier($voucher['profile']).'"';
            }
        }

        return $lines;
    }

    /**
     * On a user's first login, schedules a one-time job (named after the
     * user) that removes their account once their profile's session-timeout
     * has elapsed -- so a voucher's clock starts at first use, not creation,
     * and doesn't reset just because the customer reconnects.
     */
    private function onLoginExpiryScript(): string
    {
        // RouterOS interpolates $variables directly inside double-quoted strings, so no
        // manual concatenation is needed there -- but since this whole script becomes the
        // value of the outer on-login="..." property, every literal " below is pre-escaped
        // as \" for that outer quoting.
        return ':local u $user; :local sn (\"expire-\".$u); :if ([/system scheduler find name=$sn] = \"\") do={ '
            .':local p [/ip hotspot user get [find name=$u] profile]; :local st [/ip hotspot user profile get $p session-timeout]; '
            .':if ($st > 0s) do={ /system scheduler add name=$sn interval=$st on-event=\"/ip hotspot user remove [find name=$u]; /ip hotspot active remove [find user=$u]; /system scheduler remove [find name=$sn]\" } }';
    }

    /**
     * @param  list<array{name: string, voucher_count: int, voucher_prefix: string, voucher_code_length: int, voucher_username_password_same: bool, voucher_character_set: string}>  $profiles
     * @return list<array{profile: string, username: string, password: string}>
     */
    private function generateVoucherCodes(array $profiles): array
    {
        $vouchers = [];
        $seenUsernames = [];

        foreach ($profiles as $profile) {
            $prefix = (string) ($profile['voucher_prefix'] ?? '');
            $codeLength = max(4, (int) ($profile['voucher_code_length'] ?? 8));
            $alphabet = self::CHARACTER_SETS[$profile['voucher_character_set'] ?? 'alnum_safe'] ?? self::CHARACTER_SETS['alnum_safe'];
            $samePassword = (bool) ($profile['voucher_username_password_same'] ?? true);

            for ($i = 0; $i < max(0, (int) $profile['voucher_count']); $i++) {
                do {
                    $username = $prefix.$this->randomVoucherCode($codeLength, $alphabet);
                } while (isset($seenUsernames[$username]));

                $seenUsernames[$username] = true;

                $vouchers[] = [
                    'profile' => $profile['name'],
                    'username' => $username,
                    'password' => $samePassword ? $username : $this->randomVoucherCode($codeLength, $alphabet),
                ];
            }
        }

        return $vouchers;
    }

    private function randomVoucherCode(int $length, string $alphabet): string
    {
        $code = '';

        for ($i = 0; $i < $length; $i++) {
            $code .= $alphabet[random_int(0, strlen($alphabet) - 1)];
        }

        return $code;
    }

    /**
     * @return list<string>
     */
    private function lanPorts(string $wanPort, int $totalPorts): array
    {
        $totalPorts = max(1, $totalPorts);

        if (! preg_match('/^(.*?)(\d+)$/', $wanPort, $matches)) {
            return array_map(fn (int $n) => 'ether'.$n, range(2, max(2, $totalPorts)));
        }

        [, $prefix, $wanNumber] = $matches;
        $wanNumber = (int) $wanNumber;
        $ports = [];

        for ($n = 1; $n <= $totalPorts; $n++) {
            if ($n === $wanNumber) {
                continue;
            }

            $ports[] = $prefix.$n;
        }

        return $ports;
    }

    /**
     * @return array{host: string, gateway: string, cidr: string, range: string}
     */
    private function networkParts(string $baseCidr): array
    {
        $host = str($baseCidr)->before('/')->toString();
        $parts = explode('.', $host);
        $base = implode('.', array_slice($parts, 0, 3));

        return [
            'host' => $host,
            'gateway' => $host,
            'cidr' => $base.'.0/24',
            'range' => $base.'.10-'.$base.'.254',
        ];
    }

    private function profileIdentifier(string $name): string
    {
        return (string) str($name)->slug('-');
    }

    private function quote(?string $value): string
    {
        return str_replace('"', '\"', (string) $value);
    }
}
