<?php

namespace App\Services;

/**
 * Generates a self-contained MikroTik RouterOS hotspot configuration that
 * does not depend on this platform at all -- no WireGuard, no RADIUS, no
 * Router/Shop/Tenant record. Voucher codes become local `/ip hotspot user`
 * accounts on the router itself. Meant for the standalone "Script Generator"
 * tool (super admin only) so operators can configure any MikroTik -- with or
 * without built-in wireless, RouterOS 6 or 7 -- for a small hotspot business
 * that isn't (or isn't yet) a HotspotFreeRAD tenant.
 */
class StandaloneHotspotScriptGenerator
{
    /**
     * @param  array{
     *     hotspot_name: string,
     *     ros_version: string,
     *     has_wireless: bool,
     *     wan_port: string,
     *     lan_port: string,
     *     wireless_interface: string,
     *     hotspot_network: string,
     *     enable_mgmt_network: bool,
     *     mgmt_network: string,
     *     mgmt_password: string,
     *     profiles: list<array{name: string, download_mbps: int, upload_mbps: int, session_minutes: int, shared_users: int, voucher_count: int}>,
     * } $config
     * @return array{script: string, vouchers: list<array{profile: string, code: string}>}
     */
    public function generate(array $config): array
    {
        $vouchers = $this->generateVoucherCodes($config['profiles']);

        $lines = array_merge(
            $this->headerLines($config),
            $this->identityAndBridgeLines($config),
            $this->wanLines($config),
            $this->hotspotNetworkLines($config),
            $this->wirelessLines($config),
            $this->managementNetworkLines($config),
            $this->firewallLines($config),
            $this->profileLines($config['profiles']),
            $this->voucherLines($vouchers),
        );

        return [
            'script' => implode("\n", array_filter($lines, fn ($line) => $line !== null)),
            'vouchers' => $vouchers,
        ];
    }

    /**
     * @return list<string>
     */
    private function headerLines(array $config): array
    {
        return [
            '# Standalone MikroTik hotspot script -- generated by HotspotFreeRAD Script Generator',
            '# RouterOS '.$config['ros_version'].' / '.($config['has_wireless'] ? 'built-in wireless' : 'wired-only').' router',
            '# This script is self-contained: it does not use RADIUS, WireGuard, or any HotspotFreeRAD account.',
            '# Review port names (WAN/LAN) against your actual router before pasting.',
            '',
        ];
    }

    /**
     * @return list<string>
     */
    private function identityAndBridgeLines(array $config): array
    {
        return [
            '/system identity set name="'.$this->quote($config['hotspot_name']).'"',
            '/interface bridge add name=bridge-hotspot comment="HotspotFreeRAD standalone hotspot bridge"',
            '/interface bridge port add bridge=bridge-hotspot interface='.$config['lan_port'],
            '',
        ];
    }

    /**
     * @return list<string>
     */
    private function wanLines(array $config): array
    {
        return [
            '/interface list add name=WAN comment="Internet uplink"',
            '/interface list member add list=WAN interface='.$config['wan_port'],
            '/ip dhcp-client remove [find interface='.$config['wan_port'].']',
            '/ip dhcp-client add interface='.$config['wan_port'].' add-default-route=yes disabled=no',
            '',
        ];
    }

    /**
     * @return list<string>
     */
    private function hotspotNetworkLines(array $config): array
    {
        $network = $this->networkParts($config['hotspot_network']);

        return [
            '/ip address add address='.$network['gateway'].'/24 interface=bridge-hotspot',
            '/ip pool add name=pool-hotspot ranges='.$network['range'],
            '/ip dhcp-server add name=dhcp-hotspot interface=bridge-hotspot address-pool=pool-hotspot lease-time=30m disabled=no',
            '/ip dhcp-server network add address='.$network['cidr'].' gateway='.$network['host'].' dns-server=1.1.1.1,8.8.8.8',
            '/ip dns set allow-remote-requests=yes servers=1.1.1.1,8.8.8.8',
            '/ip hotspot profile add name=hotspot-profile hotspot-address='.$network['host'].' dns-name=hotspot.local login-by=http-pap,cookie',
            '/ip hotspot add name=hotspot1 interface=bridge-hotspot address-pool=pool-hotspot profile=hotspot-profile disabled=no',
            '/ip firewall nat add chain=srcnat out-interface='.$config['wan_port'].' action=masquerade',
            '',
        ];
    }

    /**
     * @return list<string>
     */
    private function wirelessLines(array $config): array
    {
        if (! $config['has_wireless']) {
            return [
                '# No built-in wireless -- attach an external access point to '.$config['lan_port'].' broadcasting an open SSID for the hotspot.',
                '',
            ];
        }

        $interface = $config['wireless_interface'];
        $ssid = $this->quote($config['hotspot_name']);

        if ($config['ros_version'] === '6') {
            return [
                '/interface wireless security-profiles add name=hotspot-open mode=none',
                '/interface wireless set '.$interface.' mode=ap-bridge ssid="'.$ssid.'" security-profile=hotspot-open disabled=no',
                '/interface bridge port add bridge=bridge-hotspot interface='.$interface,
                '',
            ];
        }

        return [
            '/interface wifi security add name=hotspot-open authentication-types=""',
            '/interface wifi configuration add name=hotspot-open-cfg mode=ap ssid="'.$ssid.'" security=hotspot-open',
            '/interface wifi set [find default-name='.$interface.'] configuration=hotspot-open-cfg disabled=no',
            '/interface bridge port add bridge=bridge-hotspot interface='.$interface,
            '',
        ];
    }

    /**
     * @return list<string>
     */
    private function managementNetworkLines(array $config): array
    {
        if (! $config['enable_mgmt_network']) {
            return [
                '# Management network is disabled -- administer this router over its main LAN/WAN address only.',
                '',
            ];
        }

        $network = $this->networkParts($config['mgmt_network']);
        $lines = [
            '/interface bridge add name=bridge-mgmt comment="HotspotFreeRAD standalone management bridge, isolated from hotspot clients"',
            '/ip address add address='.$network['gateway'].'/24 interface=bridge-mgmt',
            '/ip pool add name=pool-mgmt ranges='.$network['range'],
            '/ip dhcp-server add name=dhcp-mgmt interface=bridge-mgmt address-pool=pool-mgmt lease-time=8h disabled=no',
            '/ip dhcp-server network add address='.$network['cidr'].' gateway='.$network['host'].' dns-server=1.1.1.1,8.8.8.8',
        ];

        if (! $config['has_wireless']) {
            $lines[] = '# Wire a dedicated port to bridge-mgmt for management access (this router has no built-in wireless for a management SSID).';
            $lines[] = '';

            return $lines;
        }

        $interface = $config['wireless_interface'].'-mgmt';
        $password = $this->quote($config['mgmt_password']);

        if ($config['ros_version'] === '6') {
            $lines[] = '/interface wireless security-profiles add name=mgmt-sec mode=dynamic-keys authentication-types=wpa2-psk wpa2-pre-shared-key="'.$password.'"';
            $lines[] = '/interface wireless add name='.$interface.' master-interface='.$config['wireless_interface'].' ssid="'.$this->quote($config['hotspot_name'].' Mgmt').'" security-profile=mgmt-sec disabled=no';
        } else {
            $lines[] = '/interface wifi security add name=mgmt-sec authentication-types=wpa2-psk,wpa3-psk passphrase="'.$password.'"';
            $lines[] = '/interface wifi configuration add name=mgmt-cfg mode=ap ssid="'.$this->quote($config['hotspot_name'].' Mgmt').'" security=mgmt-sec';
            $lines[] = '/interface wifi add name='.$interface.' master-interface='.$config['wireless_interface'].' configuration=mgmt-cfg disabled=no';
        }

        $lines[] = '/interface bridge port add bridge=bridge-mgmt interface='.$interface;
        $lines[] = '';

        return $lines;
    }

    /**
     * @return list<string>
     */
    private function firewallLines(array $config): array
    {
        $lines = [
            '/ip firewall filter add chain=input connection-state=established,related action=accept',
            '/ip firewall filter add chain=input connection-state=invalid action=drop',
            '/ip firewall filter add chain=input in-interface=bridge-hotspot protocol=tcp dst-port=80,443,8080 action=accept comment="Hotspot captive portal ports"',
            '/ip firewall filter add chain=input in-interface-list=!WAN action=drop comment="Block other router access from hotspot clients"',
        ];

        if ($config['enable_mgmt_network']) {
            $lines[] = '/ip firewall filter add chain=input in-interface=bridge-mgmt action=accept comment="Allow the management network to reach the router"';
            $mgmtNetwork = $this->networkParts($config['mgmt_network']);
            $lines[] = '/ip firewall filter add chain=forward src-address=bridge-hotspot dst-address='.$mgmtNetwork['cidr'].' action=drop comment="Hotspot clients cannot reach the management network"';
        }

        $lines[] = '';

        return $lines;
    }

    /**
     * @param  list<array{name: string, download_mbps: int, upload_mbps: int, session_minutes: int, shared_users: int, voucher_count: int}>  $profiles
     * @return list<string>
     */
    private function profileLines(array $profiles): array
    {
        $lines = [];

        foreach ($profiles as $profile) {
            $profileName = $this->profileIdentifier($profile['name']);
            $rateLimit = $profile['upload_mbps'].'M/'.$profile['download_mbps'].'M';
            $sessionTimeout = max(1, (int) $profile['session_minutes']) * 60;

            $lines[] = '/ip hotspot user profile add name="'.$profileName.'" rate-limit='.$rateLimit.' session-timeout='.$sessionTimeout.'s shared-users='.max(1, (int) $profile['shared_users']);
        }

        $lines[] = '';

        return $lines;
    }

    /**
     * @param  list<array{profile: string, code: string}>  $vouchers
     * @return list<string>
     */
    private function voucherLines(array $vouchers): array
    {
        if ($vouchers === []) {
            return [];
        }

        $lines = ['# Voucher codes -- also listed on the printable sheet'];

        foreach ($vouchers as $voucher) {
            $lines[] = '/ip hotspot user add name="'.$voucher['code'].'" password="'.$voucher['code'].'" profile="'.$this->profileIdentifier($voucher['profile']).'"';
        }

        return $lines;
    }

    /**
     * @param  list<array{name: string, voucher_count: int}>  $profiles
     * @return list<array{profile: string, code: string}>
     */
    private function generateVoucherCodes(array $profiles): array
    {
        $vouchers = [];

        foreach ($profiles as $profile) {
            for ($i = 0; $i < max(0, (int) $profile['voucher_count']); $i++) {
                $vouchers[] = [
                    'profile' => $profile['name'],
                    'code' => $this->randomVoucherCode(),
                ];
            }
        }

        return $vouchers;
    }

    private function randomVoucherCode(): string
    {
        $alphabet = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
        $code = '';

        for ($i = 0; $i < 8; $i++) {
            $code .= $alphabet[random_int(0, strlen($alphabet) - 1)];
        }

        return $code;
    }

    /**
     * @return array{host: string, gateway: string, cidr: string, range: string}
     */
    private function networkParts(string $baseCidr): array
    {
        $host = str($baseCidr)->before('/')->toString();
        $parts = explode('.', $host);
        $base = implode('.', array_slice($parts, 0, 3));

        return [
            'host' => $host,
            'gateway' => $host,
            'cidr' => $base.'.0/24',
            'range' => $base.'.10-'.$base.'.254',
        ];
    }

    private function profileIdentifier(string $name): string
    {
        return (string) str($name)->slug('-');
    }

    private function quote(?string $value): string
    {
        return str_replace('"', '\"', (string) $value);
    }
}
